############################# Filebeat Configuration ###########################
# ============================== Filebeat inputs ===============================

filebeat.inputs:
- type: filestream
  enabled: true
  paths: 
    - /var/log/mail*.log
  fields:
    log_type: mail 

  fields_under_root: true

# ============================== Logstash Output ===============================
output.logstash:
  # The Logstash hosts
  hosts: ["192.168.8.140:5044"]


