############################# Filebeat Configuration ###########################
# ============================== Filebeat inputs ===============================

filebeat.inputs:
- type: filestream
  enabled: true
  paths: 
    - /var/log/snort/alert
  fields:
    log_type: snort

  fields_under_root: true

# ============================== Logstash Output ===============================
output.logstash:
  # The Logstash hosts
  hosts: ["192.168.8.137:5044"]

